version: '3.8'

services:
  kong-database:
    image: postgres:14
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "./db-data-kong-postgres3:/var/lib/postgresql/data"

  kong-migrations:
    # image: registry.gitlab.com/uchet.kz/pk/deploy/dev/kong:latest
    image: revomatico/docker-kong-oidc
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    # image: kong-1
    # image: registry.gitlab.com/uchet.kz/pk/deploy/dev/kong:latest
    image: revomatico/docker-kong-oidc
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      # - KONG_SSL_CERT=/certs/cert.pem
      # - KONG_SSL_CERT_KEY=/certs/key.pem
      - KONG-PLUGINS=bundled,oidc
    restart: on-failure
    ports:
      # - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    # links:
    #   - kong-database:kong-database
    depends_on:
      - kong-migrations
    volumes:
      - ./certs:/certs
    labels:
      - traefik.enable=true 
      - traefik.http.routers.kong.entrypoints=websecure
      - traefik.http.routers.kong.rule=Host(`pk-local.backend`) #&& PathPrefix(`/api/web`)
      - traefik.http.routers.kong.tls=true 
      - traefik.http.services.kong.loadbalancer.server.port=8000 

  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    volumes:
      - konga_data:/app/kongadata
    environment:
      - NODE_ENV=production

volumes:
  db-data-kong-postgres3:
  konga_data:


networks:
  default:
    external:
      name: pk_network